language: node_js
node_js:
  - "stable"
before_script:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: c5db5af6-e18a-4fe5-8df4-9d8ec5ebb8f6
  app: over-easi
  skip_cleanup: true